### ISSUE TITLE
Table prefixes

### ISSUE THREAD

**Issue by YvanDaSilva** [pschmitt/docker-owncloud#9]
The following line obliges you to have a table prefix which might not be the case if you import your owncloud database from another installation.
`DB_TABLE_PREFIX=${DB_TABLE_PREFIX:-oc_}`

Except if I missed something, setting the env var  DB_TABLE_PREFIX as follows
docker run .... `-e var=` or `-e var` will both result as variable being unset and then set by default to `oc_` in the container or set to your client env var value.

I have test with `DB_TABLE_PREFIX='' & =""` both led to prefix being set in config.php to `'""' or ''''`.

I suggest you do remove the default value for table prefixes or allow `""` or `''` to be understood as empty strings by your sed script.

**Comment by pschmitt** [comment]
PRs are welcome
